import * as vscode from 'vscode';
import * as https from 'https';
import { EpisodeStore } from './episodeStore';
import { GraphStore } from './graph/graphStore';
import { GitContext } from './gitContext';
import { NotificationService } from './NotificationService';

export class PrGenerator {
  public static async generatePrDescription(): Promise<void> {
    const notifier = NotificationService.getInstance();
    const store = EpisodeStore.get();
    const root = store.getActiveWorkspaceRoot();

    if (!root) {
      notifier.error('No active workspace open.');
      return;
    }

    const activeEp = store.getActiveEpisode(root);
    const graphStore = GraphStore.get(root);
    const subgraph = activeEp ? graphStore.getEpisodeSubgraph(activeEp.id) : graphStore.getGraph();
    const gitCtx = await GitContext.getContext(root);

    await vscode.window.withProgress(
      {
        location: vscode.ProgressLocation.Notification,
        title: 'ContextLens: Generating PR description from knowledge graph...',
        cancellable: false
      },
      async () => {
        try {
          const config = vscode.workspace.getConfiguration('contextlens');
          const apiKey = config.get<string>('apiKey') || process.env.GEMINI_API_KEY || process.env.OPENAI_API_KEY || '';
          const provider = config.get<string>('aiProvider') || 'gemini';

          let prMarkdown = '';

          if (apiKey && provider === 'gemini') {
            try {
              prMarkdown = await this.callGeminiApi(apiKey, activeEp?.name || 'Development update', subgraph, gitCtx.diff || '');
            } catch (llmErr: any) {
              console.warn('[ContextLens] BYOK LLM call failed, falling back to deterministic template:', llmErr);
              prMarkdown = this.generateDeterministicTemplate(activeEp?.name || 'Development update', subgraph, gitCtx.diff || '');
            }
          } else {
            // Offline / Zero-token deterministic template based on graph
            prMarkdown = this.generateDeterministicTemplate(activeEp?.name || 'Development update', subgraph, gitCtx.diff || '');
          }

          // Write to clipboard
          await vscode.env.clipboard.writeText(prMarkdown);

          // Open in markdown editor
          const doc = await vscode.workspace.openTextDocument({
            content: prMarkdown,
            language: 'markdown'
          });
          await vscode.window.showTextDocument(doc, {
            viewColumn: vscode.ViewColumn.Beside,
            preview: false
          });

          notifier.success('PR description generated from graph & copied to clipboard!');
        } catch (err: any) {
          notifier.error(`Failed to generate PR description: ${err.message}`);
        }
      }
    );
  }

  private static generateDeterministicTemplate(
    episodeName: string,
    subgraph: { nodes: any[]; edges: any[] },
    diff: string
  ): string {
    const files = subgraph.nodes.filter(n => n.type === 'file').map(n => n.label);
    const symbols = subgraph.nodes.filter(n => n.type === 'symbol').map(n => n.label);
    const decisions = subgraph.nodes.filter(n => n.type === 'decision');
    const commits = subgraph.nodes.filter(n => n.type === 'commit').map(n => n.label);

    let md = `# PR: ${episodeName}\n\n`;
    md += `## 🎯 Overview & Intent\n`;
    md += `This pull request encompasses work tracked in ContextLens episode **"${episodeName}"**.\n\n`;

    if (decisions.length > 0) {
      md += `### 💡 Architectural Decisions & Rationale\n`;
      for (const d of decisions) {
        md += `- **${d.label}**\n`;
        if (d.metadata?.rationale) {
          md += `  - *Why*: ${d.metadata.rationale}\n`;
        }
        if (d.metadata?.alternatives && Array.isArray(d.metadata.alternatives)) {
          md += `  - *Alternatives considered*: ${d.metadata.alternatives.join(', ')}\n`;
        }
      }
      md += `\n`;
    }

    md += `## 🔍 Key Changes\n`;
    if (files.length > 0) {
      md += `**Modified Files:**\n`;
      for (const f of files) {
        md += `- \`${f}\`\n`;
      }
      md += `\n`;
    }

    if (symbols.length > 0) {
      md += `**Defined / Modified Symbols:**\n`;
      for (const s of symbols.slice(0, 25)) {
        md += `- \`${s}\`\n`;
      }
      if (symbols.length > 25) {
        md += `- *...and ${symbols.length - 25} more symbols*\n`;
      }
      md += `\n`;
    }

    if (commits.length > 0) {
      md += `### 📜 Commits\n`;
      for (const c of commits) {
        md += `- ${c}\n`;
      }
      md += `\n`;
    }

    md += `## 🧪 Verification & Testing\n`;
    md += `- [ ] Unit tests updated and passing\n`;
    md += `- [ ] Local build verified\n`;
    md += `- [ ] Verified no unredacted credentials or secrets committed\n\n`;

    md += `---\n*Generated by ContextLens Local Graph Engine*\n`;
    return md;
  }

  private static callGeminiApi(
    apiKey: string,
    episodeName: string,
    subgraph: { nodes: any[]; edges: any[] },
    diff: string
  ): Promise<string> {
    return new Promise((resolve, reject) => {
      const prompt = `You are an expert software engineer. Generate a clear, high-quality, professional Pull Request description in GitHub Markdown based on this development episode graph and code diff.

Episode Title: ${episodeName}
Graph Nodes: ${JSON.stringify(subgraph.nodes.map(n => ({ type: n.type, label: n.label, metadata: n.metadata })))}
Graph Edges: ${JSON.stringify(subgraph.edges.map(e => ({ source: e.source, target: e.target, relation: e.relation })))}
Git Diff (truncated to 4000 chars):
${diff.slice(0, 4000)}

Instructions:
1. Include a high-level summary explaining the intent and "why" behind the changes.
2. Emphasize any architectural decisions and rationale recorded in the graph.
3. List key modified files and symbols.
4. Include a concise testing / verification checklist.
Format strictly in GitHub markdown without enclosing it in triple backtick code fences for the entire document.`;

      const requestBody = JSON.stringify({
        contents: [
          {
            parts: [{ text: prompt }]
          }
        ],
        generationConfig: {
          temperature: 0.2,
          maxOutputTokens: 2048
        }
      });

      const options = {
        hostname: 'generativelanguage.googleapis.com',
        path: `/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`,
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Content-Length': Buffer.byteLength(requestBody)
        },
        timeout: 15000
      };

      const req = https.request(options, res => {
        let data = '';
        res.on('data', chunk => { data += chunk; });
        res.on('end', () => {
          try {
            const parsed = JSON.parse(data);
            const text = parsed?.candidates?.[0]?.content?.parts?.[0]?.text;
            if (text) {
              resolve(text);
            } else {
              reject(new Error(parsed?.error?.message || 'Empty response from Gemini API'));
            }
          } catch (e) {
            reject(e);
          }
        });
      });

      req.on('error', reject);
      req.on('timeout', () => {
        req.destroy();
        reject(new Error('Request to Gemini API timed out'));
      });

      req.write(requestBody);
      req.end();
    });
  }
}
