/**
 * MCP Tool: log_ai_call
 *
 * Logs an AI tool call, prompt, and response to ContextLens for tracing.
 */

import { ToolRegistry, McpToolDefinition } from '../registry/ToolRegistry';
import { McpPermission } from '../permissions';
import { EpisodeStore } from '../../episodeStore';
import { GitContext } from '../../gitContext';
import { Redaction } from '../../redaction';
import { createHash } from 'crypto';

const logAiCall: McpToolDefinition = {
  name: 'log_ai_call',
  description: 'Log an AI tool call, prompt, and response to ContextLens for tracing',
  version: '1.0.0',
  category: 'ai',
  inputSchema: {
    type: 'object',
    properties: {
      prompt: { type: 'string', description: 'The prompt/instructions sent to the AI' },
      response: { type: 'string', description: 'The response/code generated by the AI' },
      modelName: { type: 'string', description: 'Name of the model used (optional)' },
      intent: { type: 'string', description: 'Intent tag/category (optional)' },
    },
    required: ['prompt', 'response'],
  },
  permissions: [McpPermission.WRITE, McpPermission.AI],
  handler: async (args, _context) => {
    if (!args.prompt) {
      throw new Error('promptText is required');
    }

    const gitCtx = await GitContext.getContext();
    const payload = {
      promptText: Redaction.redact(args.prompt),
      modelResponse: Redaction.redact(args.response || ''),
      source: 'mcp',
      modelName: args.modelName || 'agent',
      intentTag: args.intent || 'developer-assistant',
      branchName: gitCtx.branch || 'main',
      activeFilePath: '',
      relatedFiles: [],
      diffSnapshot: gitCtx.diff ? Redaction.redact(gitCtx.diff) : null,
      diffHash: gitCtx.diff ? createHash('md5').update(gitCtx.diff).digest('hex') : null,
    };

    EpisodeStore.get().enqueueCall(payload);

    const store = EpisodeStore.get();
    const root = store.getActiveWorkspaceRoot();
    if (root) {
      const activeEp = store.getActiveEpisode(root);
      const { GraphStore } = require('../../graph/graphStore');
      const graphStore = GraphStore.get(root);
      const promptSnippet = (args.prompt || '').slice(0, 100);
      graphStore.logDecision(promptSnippet, activeEp?.id, {
        intent: args.intent,
        modelName: args.modelName,
        source: 'mcp'
      });
    }

    return 'AI call logged successfully inside active VS Code episode!';
  },
};

ToolRegistry.getInstance().register(logAiCall);

export default logAiCall;
